### ISSUE TITLE
The plugin does not print

### ISSUE THREAD

**Issue by gabbygreat** [amoLink/bluetooth_print_plus#1]
Nice work man.

Configuring the package was a breeze, but, I am currectly facing an issue with printing

`class _BluetoothShareState extends State<BluetoothShare> {
  BluetoothPrintPlus bluetoothPrint = BluetoothPrintPlus.instance;
  BluetoothDevice? _device;

  @override
  void initState() {
    super.initState();
    _startScan();
  }

  void _startScan() async {
    bluetoothPrint.startScan(timeout: const Duration(seconds: 20));
    bluetoothPrint.state.listen((event) {
      setState(() {});
      print('EVENT IS $event');
      //0 disconnected
      //1 connected
      //11 turn on scan
      //12 turn on steady
      //13 turn off
      //10 turn off steady
    });
  }

  Future<void> _printReceipt() async {
    await bluetoothPrint.connect(_device!);

    final tscCommand = TscCommand();
    await tscCommand.cleanCommand();
    await tscCommand.cls();
    await tscCommand.size(width: 10, height: 20);
    await tscCommand.text(content: "Title", x: 10, y: 10);
    await tscCommand.text(content: "Hello", x: 10, y: 60, xMulti: 2, yMulti: 2);
    await tscCommand.print(1);
    final cmd = await tscCommand.getCommand();

    if (cmd == null) return;
    try {
      await bluetoothPrint.write(cmd);
      await bluetoothPrint.disconnect();
      ShowFlushBar.showSuccess(
        message: 'Sent',
        flushbarPosition: FlushbarPosition.TOP,
      );
    } on PlatformException {
      ShowFlushBar.showError('Failed to scan');
    } catch (error) {
      ShowFlushBar.showError('${error.runtimeType}');
    }
  }

  @override
  void dispose() async {
    bluetoothPrint.disconnect();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(
        title: 'Share to printer',
        action: [
          if (_device != null)
            IconButton(
              onPressed: _printReceipt,
              icon: const Icon(
                Icons.check_circle_outline_rounded,
              ),
            )
        ],
      ),
      body: FutureBuilder(
        future: bluetoothPrint.isOn,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const CustomLoader();
          }
          if (snapshot.data != true) {
            return const Center(
              child: Text(
                'Turn on your bluetooth',
              ),
            );
          } else {
            return StreamBuilder<List<BluetoothDevice>>(
              stream: bluetoothPrint.scanResults,
              builder: (c, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const CustomLoader();
                } else if (snapshot.hasError || snapshot.data == null) {
                  return const Center(
                    child: Text('Failed to scan'),
                  );
                } else {
                  if (snapshot.data!.isEmpty) {
                    return const EmptyWidget(
                      text: 'No bluetooth printer found',
                    );
                  }
                  return ListView(
                    children: snapshot.data!.map(
                      (d) {
                        return ListTile(
                          title: Text(d.name ?? 'Unknown'),
                          subtitle: Text(d.address ?? 'Unknown'),
                          onTap: () async {
                            setState(() {
                              if (d == _device) {
                                _device = null;
                              } else {
                                _device = d;
                              }
                            });
                          },
                          trailing:
                              _device != null && _device?.address == d.address
                                  ? const Icon(
                                      Icons.check,
                                      color: Colors.green,
                                    )
                                  : null,
                        );
                      },
                    ).toList(),
                  );
                }
              },
            );
          }
        },
      ),
    );
  }
}
`
This is my code, but, I don't know why it does not print nor throw any errors

<img width="1016" alt="Screenshot 2024-05-15 at 3 04 56 PM" src="https://github.com/amoLink/bluetooth_print_plus/assets/79731192/0e4463dc-b4b2-4fcd-9a66-0f8c95e42fc1">

The logs when I print reciept, just incase it will help

**Comment by amoLink** [comment]
Is iOS printing normal？
you Can add the TG group：https://t.me/+a7KAkNjHFS81MGNi




amoLink
***@***.***



&nbsp;

**Comment by amoLink** [comment]
> Nice work man.
> 
> Configuring the package was a breeze, but, I am currectly facing an issue with printing
> 
> `class _BluetoothShareState extends State { BluetoothPrintPlus bluetoothPrint = BluetoothPrintPlus.instance; BluetoothDevice? _device;
> 
> @OverRide void initState() { super.initState(); _startScan(); }
> 
> void _startScan() async { bluetoothPrint.startScan(timeout: const Duration(seconds: 20)); bluetoothPrint.state.listen((event) { setState(() {}); print('EVENT IS $event'); //0 disconnected //1 connected //11 turn on scan //12 turn on steady //13 turn off //10 turn off steady }); }
> 
> Future _printReceipt() async { await bluetoothPrint.connect(_device!);
> 
> ```
> final tscCommand = TscCommand();
> await tscCommand.cleanCommand();
> await tscCommand.cls();
> await tscCommand.size(width: 10, height: 20);
> await tscCommand.text(content: "Title", x: 10, y: 10);
> await tscCommand.text(content: "Hello", x: 10, y: 60, xMulti: 2, yMulti: 2);
> await tscCommand.print(1);
> final cmd = await tscCommand.getCommand();
> 
> if (cmd == null) return;
> try {
>   await bluetoothPrint.write(cmd);
>   await bluetoothPrint.disconnect();
>   ShowFlushBar.showSuccess(
>     message: 'Sent',
>     flushbarPosition: FlushbarPosition.TOP,
>   );
> } on PlatformException {
>   ShowFlushBar.showError('Failed to scan');
> } catch (error) {
>   ShowFlushBar.showError('${error.runtimeType}');
> }
> ```
> 
> }
> 
> @OverRide void dispose() async { bluetoothPrint.disconnect(); super.dispose(); }
> 
> @OverRide Widget build(BuildContext context) { return Scaffold( appBar: CustomAppBar( title: 'Share to printer', action: [ if (_device != null) IconButton( onPressed: _printReceipt, icon: const Icon( Icons.check_circle_outline_rounded, ), ) ], ), body: FutureBuilder( future: bluetoothPrint.isOn, builder: (context, snapshot) { if (snapshot.connectionState == ConnectionState.waiting) { return const CustomLoader(); } if (snapshot.data != true) { return const Center( child: Text( 'Turn on your bluetooth', ), ); } else { return StreamBuilder<List>( stream: bluetoothPrint.scanResults, builder: (c, snapshot) { if (snapshot.connectionState == ConnectionState.waiting) { return const CustomLoader(); } else if (snapshot.hasError || snapshot.data == null) { return const Center( child: Text('Failed to scan'), ); } else { if (snapshot.data!.isEmpty) { return const EmptyWidget( text: 'No bluetooth printer found', ); } return ListView( children: snapshot.data!.map( (d) { return ListTile( title: Text(d.name ?? 'Unknown'), subtitle: Text(d.address ?? 'Unknown'), onTap: () async { setState(() { if (d == _device) { _device = null; } else { _device = d; } }); }, trailing: _device != null && _device?.address == d.address ? const Icon( Icons.check, color: Colors.green, ) : null, ); }, ).toList(), ); } }, ); } }, ), ); } } ` This is my code, but, I don't know why it does not print nor throw any errors
> 
> <img alt="Screenshot 2024-05-15 at 3 04 56 PM" width="1016" src="https://private-user-images.githubusercontent.com/79731192/330836584-0e4463dc-b4b2-4fcd-9a66-0f8c95e42fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM3MzYsIm5iZiI6MTcxNTc4MzQzNiwicGF0aCI6Ii83OTczMTE5Mi8zMzA4MzY1ODQtMGU0NDYzZGMtYjRiMi00ZmNkLTlhNjYtMGY4Yzk1ZTQyZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE0MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OThhMzBlOTZlNmUzNGM2ZDk1MDZkNDE3MmEyNTI1ODUxZWFmMjBiNjE2OGNhOTg2OGVmZmFhMDU4MTg0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZcewM-uw-OtXEsLTu_osI4dyg3SPXCD60C7_3l-6Sw">
> The logs when I print reciept, just incase it will help

Is iOS printing normal？
you Can add the TG group：https://t.me/+a7KAkNjHFS81MGNi

**Comment by amoLink** [comment]
> Nice work man.
> 
> Configuring the package was a breeze, but, I am currectly facing an issue with printing
> 
> `class _BluetoothShareState extends State { BluetoothPrintPlus bluetoothPrint = BluetoothPrintPlus.instance; BluetoothDevice? _device;
> 
> @OverRide void initState() { super.initState(); _startScan(); }
> 
> void _startScan() async { bluetoothPrint.startScan(timeout: const Duration(seconds: 20)); bluetoothPrint.state.listen((event) { setState(() {}); print('EVENT IS $event'); //0 disconnected //1 connected //11 turn on scan //12 turn on steady //13 turn off //10 turn off steady }); }
> 
> Future _printReceipt() async { await bluetoothPrint.connect(_device!);
> 
> ```
> final tscCommand = TscCommand();
> await tscCommand.cleanCommand();
> await tscCommand.cls();
> await tscCommand.size(width: 10, height: 20);
> await tscCommand.text(content: "Title", x: 10, y: 10);
> await tscCommand.text(content: "Hello", x: 10, y: 60, xMulti: 2, yMulti: 2);
> await tscCommand.print(1);
> final cmd = await tscCommand.getCommand();
> 
> if (cmd == null) return;
> try {
>   await bluetoothPrint.write(cmd);
>   await bluetoothPrint.disconnect();
>   ShowFlushBar.showSuccess(
>     message: 'Sent',
>     flushbarPosition: FlushbarPosition.TOP,
>   );
> } on PlatformException {
>   ShowFlushBar.showError('Failed to scan');
> } catch (error) {
>   ShowFlushBar.showError('${error.runtimeType}');
> }
> ```
> 
> }
> 
> @OverRide void dispose() async { bluetoothPrint.disconnect(); super.dispose(); }
> 
> @OverRide Widget build(BuildContext context) { return Scaffold( appBar: CustomAppBar( title: 'Share to printer', action: [ if (_device != null) IconButton( onPressed: _printReceipt, icon: const Icon( Icons.check_circle_outline_rounded, ), ) ], ), body: FutureBuilder( future: bluetoothPrint.isOn, builder: (context, snapshot) { if (snapshot.connectionState == ConnectionState.waiting) { return const CustomLoader(); } if (snapshot.data != true) { return const Center( child: Text( 'Turn on your bluetooth', ), ); } else { return StreamBuilder<List>( stream: bluetoothPrint.scanResults, builder: (c, snapshot) { if (snapshot.connectionState == ConnectionState.waiting) { return const CustomLoader(); } else if (snapshot.hasError || snapshot.data == null) { return const Center( child: Text('Failed to scan'), ); } else { if (snapshot.data!.isEmpty) { return const EmptyWidget( text: 'No bluetooth printer found', ); } return ListView( children: snapshot.data!.map( (d) { return ListTile( title: Text(d.name ?? 'Unknown'), subtitle: Text(d.address ?? 'Unknown'), onTap: () async { setState(() { if (d == _device) { _device = null; } else { _device = d; } }); }, trailing: _device != null && _device?.address == d.address ? const Icon( Icons.check, color: Colors.green, ) : null, ); }, ).toList(), ); } }, ); } }, ), ); } } ` This is my code, but, I don't know why it does not print nor throw any errors
> 
> <img alt="Screenshot 2024-05-15 at 3 04 56 PM" width="1016" src="https://private-user-images.githubusercontent.com/79731192/330836584-0e4463dc-b4b2-4fcd-9a66-0f8c95e42fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM4MDMsIm5iZiI6MTcxNTc4MzUwMywicGF0aCI6Ii83OTczMTE5Mi8zMzA4MzY1ODQtMGU0NDYzZGMtYjRiMi00ZmNkLTlhNjYtMGY4Yzk1ZTQyZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE0MzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDI3ZWVkZmRkYzhjODhhODJjOTcyY2UzOTYyZmExOTJlMjBhZjgzYmY1N2U2Yzc5MTE5ODJmZDc4NGQ5OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KbsbpRUfoZoeGrEtSluZXvMs9o8v7OO11EdtVkbl4dw">
> The logs when I print reciept, just incase it will help

your code:
await bluetoothPrint.write(cmd);
  await bluetoothPrint.disconnect();

disconnect ????
why ?
try remove ：await bluetoothPrint.disconnect();

**Comment by gabbygreat** [comment]
Actually, if I don't disconnect, that is when I get the PlatformException
