### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by dianyulius** [amoLink/bluetooth_print_plus#10]
Hello amolink,
Do this library support on windows platform?

i tried to call this from windows 10 OS:

```
String data = text;
final command = EscCommand();
// await command.cleanCommand();
await command.text(content: data);
await command.print();
final cmd = await command.getCommand();
```

got error: 

`MissingPluginException(No implementation found for method text on channel bluetooth_print_plus_esc)`

**Comment by amoLink** [comment]
now only supports mobile devices, window should require driver installation

**Comment by dianyulius** [comment]
Okay thanks for the info
