### ISSUE TITLE
Printer not detected

### ISSUE THREAD

**Issue by fikurniawan** [amoLink/bluetooth_print_plus#12]
Good Morning. I try on my phone OPPO A60 with Android 14 OS, it is success to detect the printer and i can print the qrcode as well. But when i try it on phone: Redmi 7 and tablet: Samsung tab s4, both with Android 10 OS but none of them can detected the printer. 
Is there any limitation or OS version requirements to use the package?

Thank you.

**Comment by amoLink** [comment]
Regarding the issue of location permissions, ensure that your location permissions are enabled
If you know how to fix it, please let me know

**Comment by fikurniawan** [comment]
Yes, i have make sure the location permission is enabled and it has been allowed.
on my console i see the printer is detected, but why it is not show on the list

console:
E/BluetoothPrintPlusPlugin(11971): BlueToothName:	RPP02N
E/BluetoothPrintPlusPlugin(11971): MacAddress:	FC:58:FA:55:92:A3
E/BluetoothPrintPlusPlugin(11971): rssi:	-53
E/BluetoothPrintPlusPlugin(11971): 
E/BluetoothPrintPlusPlugin(11971): BlueToothName:	RPP02N
E/BluetoothPrintPlusPlugin(11971): MacAddress:	FC:58:FA:55:92:A3
E/BluetoothPrintPlusPlugin(11971): rssi:	-53
E/BluetoothPrintPlusPlugin(11971): 
E/BluetoothPrintPlusPlugin(11971): BlueToothName:	RPP02N
E/BluetoothPrintPlusPlugin(11971): MacAddress:	FC:58:FA:55:92:A3
E/BluetoothPrintPlusPlugin(11971): rssi:	-51
E/BluetoothPrintPlusPlugin(11971): 
E/BluetoothPrintPlusPlugin(11971): BlueToothName:	RPP02N
E/BluetoothPrintPlusPlugin(11971): MacAddress:	FC:58:FA:55:92:A3
E/BluetoothPrintPlusPlugin(11971): rssi:	-51

**Comment by amoLink** [comment]
I have a general understanding of your situation. I have an Android 10 device here, but I have a rough idea of what caused it. I will make adjustments in the future

**Comment by fikurniawan** [comment]
ok thank you for your feedback and this great package sir.

**Comment by amoLink** [comment]
fixed, you can try bluetooth_print_plus: ^2.0.3

**Comment by amoLink** [comment]
bluetooth_print_plus: ^2.0.5

**Comment by fikurniawan** [comment]
Yes, now it works sir. Thank you for your fast feedback and I will share this package to Indonesian Flutter community as the great package.

**Comment by amoLink** [comment]
Thank you
