### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by veev-sistemas** [amoLink/bluetooth_print_plus#13]
Hi, i have this error when compile project 

-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@3aea9499 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':bluetooth_print_plus'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

Flutter version -> 3.19.6
Package version -> 2.0.5

**Comment by amoLink** [comment]
You can refer to this link, hoping it will be useful to you
https://stackoverflow.com/questions/78744324/could-not-create-an-instance-of-type-com-android-build-api-variant-impl-libraryv
<img width="744" alt="Xnip2024-08-03_07-54-59" src="https://github.com/user-attachments/assets/fd58429b-0d2a-44ee-9a33-e5426b2deb54">

**Comment by amoLink** [comment]
or you can try: bluetooth_print_plus: ^2.0.6
I tried to fix it, but I haven't upgraded to the latest Android Studio and I'm not sure if it works
Good luck!

**Comment by amoLink** [comment]
hmm， In 2.0.6, I changed the Android configuration in the example...

Is that how you changed it：
in：bluetooth_print_plus/android/build.gradle 

android {
    **namespace "com.example.bluetooth_print_plus.bluetooth_print_plus"**
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
    }

    dependencies {
        testImplementation 'junit:junit:4.13.2'
        testImplementation 'org.mockito:mockito-core:5.0.0'
    }

    testOptions {
        unitTests.all {
            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
