### ISSUE TITLE
I can't print directly without navigate to new page

### ISSUE THREAD

**Issue by fikurniawan** [amoLink/bluetooth_print_plus#18]
I just trying a sample code and try to print directly without navigate to FunctionPage, but it doesn't work.
Is there a way to do that or my code is wrong?

Thank you

<img width="522" alt="ss_new_issue_bluetooth_print_plus" src="https://github.com/user-attachments/assets/a209cc31-acbd-42ca-b017-dc34ae75e277">

**Comment by amoLink** [comment]
You can put a button on this page, connect it, and then write data
Do not include it in callback methods

**Comment by fikurniawan** [comment]
ok, thank you sir, I can print directly now without navigate
