### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'TscCommand.h' file not found

### ISSUE THREAD

**Issue by samnang168** [amoLink/bluetooth_print_plus#20]
Package version:  bluetooth_print_plus: ^2.2.0
OS: MacOS Sonoma version 14.4.1 Apple M1 Chip
 
The library working fine on Android but error when starting to compile on iOS, the error shown as below, I've tried with different Flutter version:  Flutter (Channel stable, 3.24.3) and (Channel stable, 3.13.1), also tried following actions but still can't fix, and I've checked the pod project in iOS module the dependency 'GSDK' already existed, thus please advise what caused that issue and how to fix it?

- flutter clean
- flutter pub get
- flutter pub upgrade
- clean IOS build project
- delete Podfile.lock
- pod repo update
- pod install
- pod update
- open project with Runner.xcworkspace

********** Build Error *************
Running Xcode build...                                                  
Xcode build done.                                           46.8s
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'TscCommand.h' file not found
/Users/samnang/.pub-cache/hosted/pub.dev/bluetooth_print_plus-2.2.0/ios/Classes/TscCommandPlugin.m:8:8

**Comment by amoLink** [comment]
running on iOS device or iOS-simulator,
it only support iOS device

**Comment by samnang168** [comment]
> running on iOS device or iOS-simulator, it only support iOS device

I'm running on iOS device

**Comment by amoLink** [comment]
you can try:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/199fe418-5262-49e5-ad54-a4303004c612">
or restart Xcode

**Comment by samnang168** [comment]
> you can try: <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/44887344/374060635-199fe418-5262-49e5-ad54-a4303004c612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODUxMTksIm5iZiI6MTcyODI4NDgxOSwicGF0aCI6Ii80NDg4NzM0NC8zNzQwNjA2MzUtMTk5ZmU0MTgtNTI2Mi00OWU1LWFkNTQtYTQzMDMwMDRjNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA3MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTJmYzM1ZDBkYTAwYWNhNTY3NWI4MGM2NmE5YTIxNGYwY2RlZTdkZjcxY2IyMWQ1MWU1MjY3ZDYwNWM3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vz7vvbcOSHYs5ICp9NaqYwoG4ohMGlkH8t9YWeh3d50"> or restart Xcode

Yes, I already tried that.

**Comment by amoLink** [comment]
I don't know anymore
I'm normal

**Comment by amoLink** [comment]
Did you used Xcode 16 and iOS 18 ?
