### ISSUE TITLE
Device not support

### ISSUE THREAD

**Issue by AhmadFikriAS** [amoLink/bluetooth_print_plus#22]
The package does not support this device? I tried it and it did not work to move navigation in the sample project, unlike the printer which is separate from the device it worked.

![264  RTAD-HV-C1](https://github.com/user-attachments/assets/eeace2d6-a37c-4ceb-9ed4-3716a9ccf8c0)

**Comment by amoLink** [comment]
Is this a printer? What model is it ?

**Comment by AhmadFikriAS** [comment]
This is a POS device that includes a thermal printer.

Model :

• Smart Mobile POS, Display : 6.517” HD+ 720x1600 IPS
• Printer Thermal 58mm, Print Speed : 72 mm/s
• CPU Processor : Quad Core (4x2.0 Ghz A53)
• Internal Memory: 16 GB ROM + 2 GB RAM
• Wi-Fi , Bluetooth, Operating System (OS): Android 11 GO
