### ISSUE TITLE
App crash when trying to search device after exit application

### ISSUE THREAD

**Issue by fikurniawan** [amoLink/bluetooth_print_plus#23]
Search device and print works normally, but when application exit with SystemNavigator.pop();. And then start the app again and try to search device again then it suddenly crash. I also try it on sample application and it crash too.  
The app works normally again after close manually with swipe the app.

Thank you.

<img width="917" alt="image" src="https://github.com/user-attachments/assets/ffe08bea-3578-40ba-a5b5-cef7c3955a0f">

**Comment by amoLink** [comment]
Show me your code for easy replication

**Comment by fikurniawan** [comment]
This is the code from the sample app, i don't change anything  just add the exit button.

<img width="845" alt="image" src="https://github.com/user-attachments/assets/f8e02ff8-f32e-4abe-b6f4-a99788de7bfb">

**Comment by fikurniawan** [comment]
> Show me your code for easy replication

This is the code from the sample apps, i just add exit button to exit from the app. After exit the app then start again and it crash when searching device.

<img width="858" alt="image" src="https://github.com/user-attachments/assets/cf767d49-d723-4623-9894-f080a1e5d45d">

**Comment by amoLink** [comment]
Sorry, I'm working. Can you try: exit(0);

**Comment by amoLink** [comment]
Can you try: exit(0);

Or refer to: https://stackoverflow.com/questions/58680475/how-to-use-systemnavigator-pop-in-below-code-to-exit-app-in-flutter

**Comment by fikurniawan** [comment]
> Can you try: exit(0);
> 
> Or refer to: https://stackoverflow.com/questions/58680475/how-to-use-systemnavigator-pop-in-below-code-to-exit-app-in-flutter

Ok sir. Because i get off for two days I will try it on Mondayy. Thank you

**Comment by fikurniawan** [comment]
Finally it works sir. Actually i know about this exit(0) method but i'm not sure to use it. Because i read from the article it's not recommended: https://www.geeksforgeeks.org/flutter-programmatically-exit-from-the-application/ 
But it think it doesn't matter now, because it works with no problem in my case. Anyway thank you sir.

**Comment by amoLink** [comment]
SystemNavigator.pop () look like shut down java vm
I don't know how to solve this problem yet 😂

**Comment by amoLink** [comment]
Fixed, updated to: 3.3.4

Try it out

**Comment by fikurniawan** [comment]
> Fixed, updated to: 2.3.4
> 
> Try it out

i'm trying with the sample code, and it doesn't crash anymore. Thank you very much sir.
