### ISSUE TITLE
扫描蓝牙设备 _bluetoothPrintPlus.startScan

### ISSUE THREAD

**Issue by Yaozhongqiang** [amoLink/bluetooth_print_plus#24]
**首次点击【Search】** 可以正常扫描出蓝牙设备列表
**再次点击【Search】** 列表数据只显示一条
**三次点击【Search】** 列表为空
![00D7667A-4C83-4acf-8E41-5FBE4868CE46](https://github.com/user-attachments/assets/74ff50c5-157c-445d-96ae-b3459767bb24)

**Comment by amoLink** [comment]
v 2.3.3 ？

**Comment by Yaozhongqiang** [comment]
Yes

**Comment by Yaozhongqiang** [comment]
![screenshot_2024-10-24_16-52-39](https://github.com/user-attachments/assets/d3bcd0a9-bab8-4d97-a431-607dfdff9068)

**Comment by amoLink** [comment]
不是出来了， 不要一直点，点下稍等一会，安卓这问题我知道

**Comment by Yaozhongqiang** [comment]
> 版本 2.3.3？

1.在之前的版本中 扫描设备列表中会出现重复的，不知道2.3.3 有没有解决
2.我的测试流程是 点击 Search 等待10s 再次点击 Search

**Comment by amoLink** [comment]
重复的交给外界处理，自己过滤下就行

**Comment by Yaozhongqiang** [comment]
> 不是出来了， 不要一直点，点下稍等一会，安卓这问题我知道

加油💪，希望插件持续更新做的更完善更好用，

**Comment by amoLink** [comment]
嗯嗯，有什么想法可以交流下

**Comment by amoLink** [comment]
> > 不是出来了， 不要一直点，点下稍等一会，安卓这问题我知道
> 
> 加油💪，希望插件持续更新做的更完善更好用，

嗯嗯，有什么想法有交流下

**Comment by Yaozhongqiang** [comment]
> 重复的交给外界处理，自己过滤下就行

**Comment by amoLink** [comment]
嗯嗯，有好的方案可以贴出来
这问题后面有时间我也会看能不能优化的

**Comment by Yaozhongqiang** [comment]
> 嗯嗯，有好的方案可以贴出来 这问题后面有时间我也会看能不能优化的
ok👍

**Comment by amoLink** [comment]
已修复，更新到：3.3.4
试下

**Comment by Yaozhongqiang** [comment]
> 已修复，更新到：2.3.4 试下

棒👍
