### ISSUE TITLE
TscImageCmd 打印 Image

### ISSUE THREAD

**Issue by Yaozhongqiang** [amoLink/bluetooth_print_plus#25]
### Hi~亲爱的小哥，请教一下打印图片的问题：
**前提**：标签的内容只有一个图片。
**当前测试**：标签中的内容是图片的原尺寸，不是自适应 ，只显示出部分信息。
**图片**：![1](https://github.com/user-attachments/assets/f14b7d39-57d0-4050-9596-91a5451a23fd)
**问题**：① 打印标签的图片尺寸能否可以设置并且能自适应显示。
                 ② 是否在转换图片的时候指定尺寸？![3](https://github.com/user-attachments/assets/7741d778-df0a-405c-8d16-24f00d58baab)

**Comment by Yaozhongqiang** [comment]
> ### Hi~亲爱的小哥，请教一下打印图片的问题：
> **前提**：标签的内容只有一个图片。 **当前测试**：标签中的内容是图片的原尺寸，不是自适应 ，只显示出部分信息。 **图片**：![1](https://private-user-images.githubusercontent.com/51535276/380031568-f14b7d39-57d0-4050-9596-91a5451a23fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzc0MzcsIm5iZiI6MTcyOTgzNzEzNywicGF0aCI6Ii81MTUzNTI3Ni8zODAwMzE1NjgtZjE0YjdkMzktNTdkMC00MDUwLTk1OTYtOTFhNTQ1MWEyM2ZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDBhMTQ2MzhlM2E4MWViNTYxNDFlMTYyZTE3ODE0OGEwNzI0YzlhMTYwOTk2MTBmMDFjOThhNWU0ZTQ5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NiJehJqpzij7chFYbWfpgVqbwu4u4QBP3mT89C7It3c) **问题**：① 打印标签的图片尺寸能否可以设置并且能自适应显示。 ② 是否在转换图片的时候指定尺寸？![3](https://private-user-images.githubusercontent.com/51535276/380034546-7741d778-df0a-405c-8d16-24f00d58baab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzc0MzcsIm5iZiI6MTcyOTgzNzEzNywicGF0aCI6Ii81MTUzNTI3Ni8zODAwMzQ1NDYtNzc0MWQ3NzgtZGYwYS00MDVjLThkMTYtMjRmMDBkNThiYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDQ4MzJlY2RiYzcyNTBkZGI5N2VhNDBjNWQzN2MzMTg4YTIwNGY4NzAzNjlkMWIzNDQ0ZDRhOGI1MTY4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ac_wF2btzvKsyzwg3aPmP-lsiGiJIelQCxmVpZVtLWU)

**Comment by Yaozhongqiang** [comment]
![2](https://github.com/user-attachments/assets/2abe9db6-4f9e-4ce7-ba61-b8a844b9a92d)
这张标签是制定了尺寸
` const double dpi = 240.0; // 可以根据需要调整 DPI
        final int width = (page.width * dpi / 72).round(); // 计算宽度
        final int height = (page.height * dpi / 72).round(); // 计算高度
        final pageImage = await page.render(
            width: width.toDouble(),
              height: height.toDouble(),
            format: PdfPageImageFormat.png,
            backgroundColor: '#FFFFFF',
            forPrint: true);
        images.add(pageImage?.bytes);
        page.close();`
**效果** 可以显示完全，但文字很糊。

**Comment by amoLink** [comment]
自行调整！！！

**Comment by Yaozhongqiang** [comment]
> 自行调整！！！

好吧，感谢！
