### ISSUE TITLE
Print Image ESC command not completed

### ISSUE THREAD

**Issue by vukhacbiet** [amoLink/bluetooth_print_plus#26]
I use example app with
Model: Xprinter XP-P323B
Mode: ESC command

It write half image and then write chinese letters

Please help

![image](https://github.com/user-attachments/assets/48e4e4ad-bd15-4ab0-bf66-06d6a195d219)
![image](https://github.com/user-attachments/assets/cce8ab06-ed50-47c4-bf01-e6d230fe7480)

**Comment by vukhacbiet** [comment]
It's 80mm printer

**Comment by amoLink** [comment]
I don't know
you can try tsc or cpcl
