### ISSUE TITLE
Can't print image with TSC command in iOS device

### ISSUE THREAD

**Issue by mrizkynurfajrie** [amoLink/bluetooth_print_plus#28]
Hi, really appreciate with this great work!

I encountered a problem here with TSC Command in iOS device. I try to print an image but there is nothing happens, i wrap my code with try catch but no catched any errors.

Here is my code :
<img width="594" alt="Screenshot 2024-11-04 at 17 02 33" src="https://github.com/user-attachments/assets/5f76ef67-89d8-402c-9bcf-11f1867e86d6">

Here is what shown in debug log console : 
<img width="1168" alt="Screenshot 2024-11-04 at 16 13 53" src="https://github.com/user-attachments/assets/f79db8f9-b948-4ad6-9012-ec89d537f2ec">

I had no idea with this problems.

Thanks

**Comment by amoLink** [comment]
I don't know
No printer to debug...

**Comment by mrizkynurfajrie** [comment]
> I don't know No printer to debug...
> 
> text/QR_code/barcode print ok ?

Yeah, print with Text or QR Code just going well. This happen only with Image. My printer support TSC/TSPL, CPCL, and ESC Command. I tried with all these command always works with text or qrcode, but still doesn't print anything with image.

**Comment by mrizkynurfajrie** [comment]
> You may need to wait a little longer, as the image data is quite large



> You may need to wait a little longer, as the image data is quite large

I've tried smaller image data still doesn't printed. 
I send Uint8List data to log and the result show bunch of Uint8 data which is image data isn't empty. I put any log before & after load image data and those log printed in debug console.

I've had no idea with this, because there is no error log with or w/o try catch handler even from native side.

disclaimer:
But, i still really appreciate with your works. This is one of the most helpfull package in my project.

**Comment by amoLink** [comment]
Alternatively, you can try switching to CPLC to print images

**Comment by amoLink** [comment]
Adjust the instruction sequence. Some printer instructions have specific requirements, and CLS must be placed after size
`
await tscCommand.cleanCommand();
await tscCommand.size(width: 76, height: 130);
await tscCommand.cls();
`

**Comment by amoLink** [comment]
> > You may need to wait a little longer, as the image data is quite large
> 
> > You may need to wait a little longer, as the image data is quite large
> 
> I've tried smaller image data still doesn't printed. I send Uint8List data to log and the result show bunch of Uint8 data which is image data isn't empty. I put any log before & after load image data and those log printed in debug console.
> 
> I've had no idea with this, because there is no error log with or w/o try catch handler even from native side.
> 
> disclaimer: But, i still really appreciate with your works. This is one of the most helpfull package in my project.

Adjust the instruction sequence. Some printer instructions have specific requirements, and CLS must be placed after size
await tscCommand.cleanCommand();
await tscCommand.size(width: 76, height: 130);
await tscCommand.cls();

**Comment by mrizkynurfajrie** [comment]
> > > You may need to wait a little longer, as the image data is quite large
> > 
> > 
> > > You may need to wait a little longer, as the image data is quite large
> > 
> > 
> > I've tried smaller image data still doesn't printed. I send Uint8List data to log and the result show bunch of Uint8 data which is image data isn't empty. I put any log before & after load image data and those log printed in debug console.
> > I've had no idea with this, because there is no error log with or w/o try catch handler even from native side.
> > disclaimer: But, i still really appreciate with your works. This is one of the most helpfull package in my project.
> 
> Adjust the instruction sequence. Some printer instructions have specific requirements, and CLS must be placed after size
> 
> `await tscCommand.cleanCommand();` `await tscCommand.size(width: 76, height: 130);` `await tscCommand.cls();`

Ah, after adjust the instruction sequence, i've succesfully print image data. I put CLS command after image command.
Thank you so much!.

**Comment by mrizkynurfajrie** [comment]
> > > You may need to wait a little longer, as the image data is quite large
> > 
> > 
> > > You may need to wait a little longer, as the image data is quite large
> > 
> > 
> > I've tried smaller image data still doesn't printed. I send Uint8List data to log and the result show bunch of Uint8 data which is image data isn't empty. I put any log before & after load image data and those log printed in debug console.
> > I've had no idea with this, because there is no error log with or w/o try catch handler even from native side.
> > disclaimer: But, i still really appreciate with your works. This is one of the most helpfull package in my project.
> 
> Adjust the instruction sequence. Some printer instructions have specific requirements, and CLS must be placed after size
> 
> `await tscCommand.cleanCommand();` `await tscCommand.size(width: 76, height: 130);` `await tscCommand.cls();`

I'm sorry,  but i have one question with image command. How can i configure image size to be printed?

**Comment by mrizkynurfajrie** [comment]
> if your image size is: 400 × 225, For printers, the size may be： 200 DPI: 50mm x 28.1mm 300 DPI: 33.3mm x 18.75mm
> 
> 200 DPI: 1mm = 8dot 300 DPI: 1mm = 12dot

Okay, thank you for your great works & your response.
I'll close this thread.
