### ISSUE TITLE
希望增加获取连接状态

### ISSUE THREAD

**Issue by Yaozhongqiang** [amoLink/bluetooth_print_plus#29]
只发现在状态监听中有判断` case BPPState.deviceConnected:
          setState(() {
            if (_device == null) return;
            connected = true;
            Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => FunctionPage(_device!)));
          });
          break;`

**Comment by Yaozhongqiang** [comment]
> 只发现在状态监听中有判断` case BPPState.deviceConnected: setState(() { if (_device == null) return; connected = true; Navigator.push( context, MaterialPageRoute( builder: (context) => FunctionPage(_device!))); }); break;`

**Comment by Yaozhongqiang** [comment]
`_bluetoothPrintPlus.isScanning.listen((event) {
        print('********** isScanning: $event **********');
        if (mounted) {
          setState(() {});
        }
      });`

**Comment by Yaozhongqiang** [comment]
增加连接状态的查询很方便，用来【重新连接】的判断，减少【扫描】的调用

**Comment by Yaozhongqiang** [comment]
1. ` private ThreadPoolManager threadPoolManager;`

2.  ` case "isConnected":
        result.success(threadPoolManager!=null);
        break;`

3. `private final StreamHandler stateHandler = new StreamHandler() {
    private EventSink sink;
    private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
      @Override
      public void onReceive(Context context, Intent intent) {
        ...
        if (BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)) {
         ...
          threadPoolManager = null;
         ...
        } else if (BluetoothDevice.ACTION_ACL_CONNECTED.equals(action)) {
          ...
        } else if (BluetoothDevice.ACTION_ACL_DISCONNECTED.equals(action)) {
          ...
          threadPoolManager = null;
         ...
        }
      }
    };
`

4. `Future<bool?> isConnected() => _channel.invokeMethod('isConnected');`
看一下这样是否可行？？？

**Comment by amoLink** [comment]
> > 
> 
> ```
>     private ThreadPoolManager threadPoolManager;
> ```
> 
> > 
> 
> ```
>     case "isConnected":
>     result.success(threadPoolManager!=null);
>     break;
> ```
> 
> > 
> 
> ```
>     public void connect(final String mac) {
>         threadPoolManager = ThreadPoolManager.getInstance();
>         threadPoolManager.addTask(new Runnable() {
>          ...
>         });
>       }
> ```
> 
> > 
> 
> ```
>      private final StreamHandler stateHandler = new StreamHandler() {
>      private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
>       @Override
>       public void onReceive(Context context, Intent intent) {
>         ...
>         if (BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)) {
>          ...
>           threadPoolManager = null;
>          ...
>         } else if (BluetoothDevice.ACTION_ACL_DISCONNECTED.equals(action)) {
>           ...
>           threadPoolManager = null;
>          ...
>         }
>       }
>     };
> ```
> 
> > 
> 
> ```
>    Future<bool?> isConnected() => _channel.invokeMethod('isConnected');
> ```
> 
> 看一下这样是否可行？？？

在状态的监听里面有了，没必要添加重复的东西

**Comment by amoLink** [comment]
> > 
> 
> ```
>     private ThreadPoolManager threadPoolManager;
> ```
> 
> > 
> 
> ```
>     case "isConnected":
>     result.success(threadPoolManager!=null);
>     break;
> ```
> 
> > 
> 
> ```
>     public void connect(final String mac) {
>         threadPoolManager = ThreadPoolManager.getInstance();
>         threadPoolManager.addTask(new Runnable() {
>          ...
>         });
>       }
> ```
> 
> > 
> 
> ```
>      private final StreamHandler stateHandler = new StreamHandler() {
>      private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
>       @Override
>       public void onReceive(Context context, Intent intent) {
>         ...
>         if (BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)) {
>          ...
>           threadPoolManager = null;
>          ...
>         } else if (BluetoothDevice.ACTION_ACL_DISCONNECTED.equals(action)) {
>           ...
>           threadPoolManager = null;
>          ...
>         }
>       }
>     };
> ```
> 
> > 
> 
> ```
>    Future<bool?> isConnected() => _channel.invokeMethod('isConnected');
> ```
> 
> 看一下这样是否可行？？？

另外不要添加额外的工作量，你的时间宝贵我的时间也宝贵...

**Comment by Yaozhongqiang** [comment]
> > > 
> > 
> > 
> > ```
> >     private ThreadPoolManager threadPoolManager;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >     case "isConnected":
> >     result.success(threadPoolManager!=null);
> >     break;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >     public void connect(final String mac) {
> >         threadPoolManager = ThreadPoolManager.getInstance();
> >         threadPoolManager.addTask(new Runnable() {
> >          ...
> >         });
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >      private final StreamHandler stateHandler = new StreamHandler() {
> >      private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
> >       @Override
> >       public void onReceive(Context context, Intent intent) {
> >         ...
> >         if (BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)) {
> >          ...
> >           threadPoolManager = null;
> >          ...
> >         } else if (BluetoothDevice.ACTION_ACL_DISCONNECTED.equals(action)) {
> >           ...
> >           threadPoolManager = null;
> >          ...
> >         }
> >       }
> >     };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >    Future<bool?> isConnected() => _channel.invokeMethod('isConnected');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看一下这样是否可行？？？
> 
> 在状态的监听里面有了，没必要添加重复的东西


> > > 
> > 
> > 
> > ```
> >     private ThreadPoolManager threadPoolManager;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >     case "isConnected":
> >     result.success(threadPoolManager!=null);
> >     break;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >     public void connect(final String mac) {
> >         threadPoolManager = ThreadPoolManager.getInstance();
> >         threadPoolManager.addTask(new Runnable() {
> >          ...
> >         });
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >      private final StreamHandler stateHandler = new StreamHandler() {
> >      private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
> >       @Override
> >       public void onReceive(Context context, Intent intent) {
> >         ...
> >         if (BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)) {
> >          ...
> >           threadPoolManager = null;
> >          ...
> >         } else if (BluetoothDevice.ACTION_ACL_DISCONNECTED.equals(action)) {
> >           ...
> >           threadPoolManager = null;
> >          ...
> >         }
> >       }
> >     };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > ```
> >    Future<bool?> isConnected() => _channel.invokeMethod('isConnected');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看一下这样是否可行？？？
> 
> 另外不要添加额外的工作量，你的时间宝贵我的时间也宝贵...

🙂，监听里是有但貌似不能独立执行吧！没关系！我只是使用时觉得这样更方便，项目是你的，决定权在你。
