### ISSUE TITLE
iOS issue: 'TscCommand.h' & 'EscCommand.h' is missing

### ISSUE THREAD

**Issue by KeroJohn97** [amoLink/bluetooth_print_plus#3]
Package version: v1.5.2
While I was running the application, this error was thrown and the app build failed. And they do not exist anywhere.

Error: 'TscCommand.h' file not found
Error: 'EscCommand.h' file not found

**Comment by KeroJohn97** [comment]
Not related to package

**Comment by amoLink** [comment]
You may not have executed pod install
