### ISSUE TITLE
Print TSC Image not working

### ISSUE THREAD

**Issue by seetherisingazeez** [amoLink/bluetooth_print_plus#30]
I'm trying to print an image using the TSC command but nothing happens

For your reference here's my code.
<pre>
  TscCommand tscCommand = TscCommand();
    await tscCommand.cleanCommand();
    await tscCommand.cls();
    await tscCommand.size(width: 40, height: 60);
    await tscCommand.image(image: resizedImageBytes, x: 0, y: 0);
    await tscCommand.print(copies);
    final cmd = await tscCommand.getCommand();
    bluetoothPrint.write(command);
</pre>

Am I missing something here? 
Please help.

**Comment by amoLink** [comment]
> I'm trying to print an image using the TSC command but nothing happens
> 
> For your reference here's my code.
> 
>   TscCommand tscCommand = TscCommand();
>     await tscCommand.cleanCommand();
>     await tscCommand.cls();
>     await tscCommand.size(width: 40, height: 60);
>     await tscCommand.image(image: resizedImageBytes, x: 0, y: 0);
>     await tscCommand.print(copies);
>     final cmd = await tscCommand.getCommand();
>     bluetoothPrint.write(command);
> Am I missing something here? Please help.

Adjust the instruction sequence. Some printer instructions have specific requirements, and CLS must be placed after size

await tscCommand.cleanCommand();
await tscCommand.size(width: 76, height: 130);
await tscCommand.cls();
....

**Comment by seetherisingazeez** [comment]
Still no luck. 
I'm using RP311 Shipping Express Waybill Label Printer

**Comment by amoLink** [comment]
I don't know
