### ISSUE TITLE
(TSC Command) Print QR Code multiple copies with different value each copies

### ISSUE THREAD

**Issue by mrizkynurfajrie** [amoLink/bluetooth_print_plus#31]
Hello,

I want to ask how to print QR Code (TSC Command) with multiple copies and each copies have different value.
Here is my code : 

<img width="538" alt="Screenshot 2024-11-07 at 08 57 12" src="https://github.com/user-attachments/assets/04a8fef4-a510-4a86-8b4e-ce1b1d6d17e1">

The problem with my code is, all the data inside listQr printed on 1 copies and the QR & Text are stacked.

![Uploading ImportedPhoto_1730944922909.jpg…]()

**Comment by amoLink** [comment]
I don't know...
