### ISSUE TITLE
Incomplete Web Support

### ISSUE THREAD

**Issue by charden-daxicen** [amoLink/bluetooth_print_plus#32]
The package is labelled to Support Web. But am getting this error when trying to run for the web

```
org-dartlang-app:/web_plugin_registrant.dart:9:8: Error: Error when reading '../../../../../../.pub-cache/hosted/pub.dev/bluetooth_print_plus-2.3.4/lib/bluetooth_print_plus_web.dart': No such file or directory
import 'package:bluetooth_print_plus/bluetooth_print_plus_web.dart';
       ^
org-dartlang-app:/web_plugin_registrant.dart:22:3: Error: Undefined name 'BluetoothPrintPlusWeb'.
  BluetoothPrintPlusWeb.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

**My Environment**
Flutter Version:  3.24.3  
Dart Version:  3.5.3

**Comment by amoLink** [comment]
Only supports iOS and Android

**Comment by charden-daxicen** [comment]
Currently you get build errors by just including it on dependencies.

Can it be in such a way the developer can include it 
without getting build errors for web.  When using it the developer will be responsible to activate the feature on Android and iOS only
