### ISSUE TITLE
Bluetooth Connection over android devices always disconnecting after connected

### ISSUE THREAD

**Issue by mrizkynurfajrie** [amoLink/bluetooth_print_plus#34]
Hi, can you check this issue? 
I always get disconnecting state after connected to my device. Only happen in android device.

<img width="1393" alt="Screenshot 2024-11-22 at 10 13 46" src="https://github.com/user-attachments/assets/ba7dc914-df9d-4109-9f63-dc0cd62ce2b6">

Appreciate any advices

**Comment by amoLink** [comment]
> Hi, can you check this issue? I always get disconnecting state after connected to my device. Only happen in android device.
> 
> <img alt="Screenshot 2024-11-22 at 10 13 46" width="1393" src="https://private-user-images.githubusercontent.com/86530834/388786723-ba7dc914-df9d-4109-9f63-dc0cd62ce2b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MzY3NDcsIm5iZiI6MTczMjkzNjQ0NywicGF0aCI6Ii84NjUzMDgzNC8zODg3ODY3MjMtYmE3ZGM5MTQtZGY5ZC00MTA5LTlmNjMtZGMwY2Q2MmNlMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDAzMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OWMzNGY5ZDBhZThkOTUwZGZlZTc4M2ZmZTdlNjBlZjE5ZjAzODVkYTEwNTc4YmFlMzk0MDkxZGQwZTkzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NXVUiN4bfqvOCUEPVE_Zv_YACbXwrLmFsjz1oyopWXE">
> Appreciate any advices

try：bluetooth_print_plus: ^2.4.0

**Comment by hizamirashid** [comment]
its still happening. it get disconnected right after connected. then connected again. continues looping.
