### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by rishad13** [amoLink/bluetooth_print_plus#35]
hy can i get permission to add a new branch to add doc for ESCC comments

**Comment by amoLink** [comment]
> hy can i get permission to add a new branch to add doc for ESCC comments

I didn't understand what you meant

**Comment by amoLink** [comment]
> hy can i get permission to add a new branch to add doc for ESCC comments
What do you want to add? Send it out and have a look

**Comment by rishad13** [comment]
i want to contribute something , if that is valuable you can mrg to main

**Comment by amoLink** [comment]
> i want to contribute something , if that is valuable you can mrg to main

Of course, if it's useful, I will adopt it.
What do you want to add?

**Comment by rishad13** [comment]
![Screenshot 2024-11-30 152125](https://github.com/user-attachments/assets/d79d3acb-fc7b-4955-806f-f0c3db8ea8ad)

**Comment by rishad13** [comment]
> > i want to contribute something , if that is valuable you can mrg to main
> 
> Of course, if it's useful, I will adopt it. What do you want to add?

add doc for class EscCommand {

**Comment by amoLink** [comment]
> ![Screenshot 2024-11-30 152125](https://private-user-images.githubusercontent.com/74727518/391227614-d79d3acb-fc7b-4955-806f-f0c3db8ea8ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjA3OTIsIm5iZiI6MTczMjk2MDQ5MiwicGF0aCI6Ii83NDcyNzUxOC8zOTEyMjc2MTQtZDc5ZDNhY2ItZmM3Yi00OTU1LTgwNmYtZjBjM2RiOGVhOGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA5NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYWE2ZTFmM2IzZTY0NjNhZDUzOWRlZjM4ZDEyNjQxMTY4Y2Y5NjMyNmU3MWU5ZWNhZmZhOWQwZmE1MGU2ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tXvY9QSIvfNx1DVkuRRRit0atg205pwylO6rnpFk3Vs)

You may need to fork my code and submit a Pull request
Someone has done this before
<img width="522" alt="image" src="https://github.com/user-attachments/assets/1aaf7ce2-376e-477e-bcb9-6c64626631d2">

**Comment by rishad13** [comment]
ok letme try

**Comment by amoLink** [comment]
> ok letme try

Great！ I'll take a look later

**Comment by amoLink** [comment]
> ok letme try

Thank you, your contribution will be released in the next version
