### ISSUE TITLE
Print Out tscCommand

### ISSUE THREAD

**Issue by yusfiadil** [amoLink/bluetooth_print_plus#4]
my code :
![image](https://github.com/amoLink/bluetooth_print_plus/assets/26054562/bfc6c0ce-78c6-4497-9611-e8f28a4cda05)

result :
![WhatsApp Image 2024-06-07 at 15 32 37](https://github.com/amoLink/bluetooth_print_plus/assets/26054562/3e6d64f1-813a-42a0-bce7-2794119c2b5b)

How did it happen ?

**Comment by amoLink** [comment]
You need to determine the command type for your printer, and then run the demo to select the tsc cpcl esc command

**Comment by yusfiadil** [comment]
i'm using tsc. my command size,etc.... why follow to print out ? it shouldn't be

**Comment by amoLink** [comment]
I also encountered a very confirmed one, but later it wasn't

**Comment by yusfiadil** [comment]
model VSC TM-80D
and I test in printer thermal ZJiang model ZJ-5809. same issue.

**Comment by amoLink** [comment]
try run the demo to select cpcl  or esc command，I didn't find any useful information about VSC TM-80D

**Comment by yusfiadil** [comment]
VSC TM-80 D is a printer brand in my country. But I have a thermal printer ZJiang model ZJ-5809, and the same issue occurs where the print command is also printed. It should only print the text, not the command

any solution ?

**Comment by amoLink** [comment]
ZJ-5809 is ESC/POS
http://www.zjiang.com/en/init.php/product/index?id=57
<img width="600" alt="Xnip2024-06-07_22-08-47" src="https://github.com/amoLink/bluetooth_print_plus/assets/44887344/6568cc50-05dc-4d65-b80c-5dd4fbff3614">

**Comment by yusfiadil** [comment]
Is there an example of an ESC command for printing text? Because the ESC commands I found only have examples for printing images.

**Comment by amoLink** [comment]
A new version will be released in a few days

**Comment by yusfiadil** [comment]
Great, I'll be looking forward to the new version.

**Comment by amoLink** [comment]
Updated, please update to version 2.0.0

**Comment by yusfiadil** [comment]
ok, i will try it. thanks.
