### ISSUE TITLE
await blocks the function process, causing the code behind await to not be executed

### ISSUE THREAD

**Issue by maxfrees** [amoLink/bluetooth_print_plus#42]
await blocks the function process, causing the code behind await to not be executed

![34d7477974033bcc60533af69765fdd4](https://github.com/user-attachments/assets/7b496320-5e75-4cb1-98ef-7258d69ae386)

It seems like disconnect connect has that problem

**Comment by amoLink** [comment]
fixed, update to bluetooth_print_plus: ^2.4.2

**Comment by amoLink** [comment]
我这挺正常的
