### ISSUE TITLE
No San Result Return

### ISSUE THREAD

**Issue by ThanHtikeAung** [amoLink/bluetooth_print_plus#8]
**Environment** - Samsung Galaxy Tab A (2016) with android version 7.0.
**Issue** - Tried to search Bluetooth devices as shown in example code but no results return. But error message in debug console logs the list of Bluetooth devices.

`E/BluetoothPrintPlusPlugin(14142): BlueToothName: xxxxx`
`E/BluetoothPrintPlusPlugin(14142): MacAddress:	xxxxxxx`
`E/BluetoothPrintPlusPlugin(14142): rssi:	-43`

Thanks

**Comment by amoLink** [comment]
There's no such low version phone to test

**Comment by ARIATheCarl** [comment]
I use 1.5.2 version android can show device at list, but 2.0.2 version can't.

**Comment by amoLink** [comment]
fixed, you can try bluetooth_print_plus: ^2.0.5
