### ISSUE TITLE
cur device status: 12

### ISSUE THREAD

**Issue by naskapal** [amoLink/bluetooth_print_plus#9]
Device: Samsung A05S
Issue: Unable to find bluetooth devices

When I initiated the screen using the sample, message like this:
`I/flutter (27541): ******************* cur device status: 12`

and when I tried to tap the search button, the console prints out error like this

`D/BluetoothPrintPlusPlugin(27541): start scan 
I/BluetoothAdapter(27541): startDiscovery
E/MethodChannel#bluetooth_print_plus/methods(27541): Failed to handle method call
E/MethodChannel#bluetooth_print_plus/methods(27541): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at com.example.bluetooth_print_plus.bluetooth_print_plus.BluetoothPrintPlusPlugin.onMethodCall(BluetoothPrintPlusPlugin.java:214)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at android.os.Looper.loopOnce(Looper.java:230)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at android.os.Looper.loop(Looper.java:319)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at android.app.ActivityThread.main(ActivityThread.java:8900)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/MethodChannel#bluetooth_print_plus/methods(27541): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/DartMessenger(27541): Uncaught exception in binary message listener
E/DartMessenger(27541): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(27541): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/DartMessenger(27541): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:287)
E/DartMessenger(27541): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(27541): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(27541): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(27541): 	at android.os.Handler.handleCallback(Handler.java:958)
E/DartMessenger(27541): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(27541): 	at android.os.Looper.loopOnce(Looper.java:230)
E/DartMessenger(27541): 	at android.os.Looper.loop(Looper.java:319)
E/DartMessenger(27541): 	at android.app.ActivityThread.main(ActivityThread.java:8900)
E/DartMessenger(27541): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(27541): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/DartMessenger(27541): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

Thanks

**Comment by amoLink** [comment]
sorry. I don't have that device for testing. My phone test is normal

**Comment by naskapal** [comment]
I'm wondering where can I find the list of codes such as 12, 13 10? I know 1 is connected and 0 is diconnected, but I wanted to know the other

**Comment by naskapal** [comment]
nvm, 12 means the bluetooth is active, but location service is not on, solved it, thanks! 😁
